# implicitly
disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- HappLabsDemo/Resources/R.generated.swift

line_length:
    warning: 400
    error: 500
    
function_body_length:
    warning: 100
    error: 120
    
function_parameter_count:
    warning: 8
    error: 10

opt_in_rules: # some rules are only opt-in
- force_unwrapping

